"""ajuste em Pick

Revision ID: 4099c5843227
Revises: 1d3b94a6e7fd
Create Date: 2024-03-10 08:52:58.510032
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4099c5843227'
down_revision = '1d3b94a6e7fd'
branch_labels = None
depends_on = None

def upgrade():
    # Commands auto-generated by Alembic - adjusted for named foreign keys
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('round_id',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_nullable=True)

    with op.batch_alter_table('picks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('position', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('player_id', sa.Integer(), nullable=False))
        batch_op.alter_column('game_id',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_nullable=True)
        batch_op.alter_column('round_id',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_nullable=True)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_nullable=True)
        batch_op.alter_column('tournament_id',
                              existing_type=sa.INTEGER(),
                              nullable=False,
                              existing_nullable=True)
        # Ensure to name your foreign key constraints
        batch_op.create_foreign_key('fk_picks_player_id', 'players', ['player_id'], ['id'])
        batch_op.create_foreign_key('fk_picks_user_id', 'users', ['user_id'], ['id'])

def downgrade():
    # Reverse the changes made in the upgrade.
    with op.batch_alter_table('picks', schema=None) as batch_op:
        # Use the correct names for dropping constraints
        batch_op.drop_constraint('fk_picks_player_id', type_='foreignkey')
        batch_op.drop_constraint('fk_picks_user_id', type_='foreignkey')
        batch_op.alter_column('tournament_id',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_nullable=False)
        batch_op.alter_column('user_id',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_nullable=False)
        batch_op.alter_column('round_id',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_nullable=False)
        batch_op.alter_column('game_id',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_nullable=False)
        batch_op.drop_column('player_id')
        batch_op.drop_column('position')

    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.alter_column('round_id',
                              existing_type=sa.INTEGER(),
                              nullable=True,
                              existing_nullable=False)
