"""Adiciona user_id a games

Revision ID: dcb65c720274
Revises: 4099c5843227
Create Date: 2024-03-10 23:47:32.741841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcb65c720274'
down_revision = '4099c5843227'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        # Nomeie explicitamente a constraint de chave estrangeira
        batch_op.create_foreign_key('fk_games_user_id', 'users', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('games', schema=None) as batch_op:
        # Use o mesmo nome fornecido durante o upgrade para remover a constraint
        batch_op.drop_constraint('fk_games_user_id', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
